- hosts: localhost
  gather_facts: no
  vars_files: vars/dnac_vars_pod#.yaml
  vars:
    dnac_conn: &dnac_conn
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_debug: "{{dnac_debug}}"    
      
 
  tasks:
    - name: Get System INfo
      cisco.dnac.system_health_info:
        <<: *dnac_conn
        summary: true
      register: result

    - name: Show Health
      debug:
        msg:
          - "{{ result }}"
