- hosts: localhost
  gather_facts: no
  vars_files: vars/dnac_vars_pod1.yaml
  vars:
    dnac_conn: &dnac_conn
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_debug: "{{dnac_debug}}"  

  tasks:
    - name: Create site - area, building and floor
      cisco.dnac.site_intent:
        <<: *dnac_conn
        state: "merged"
        config:
        - type: "{{ item.type }}"
          site: "{{ item.site }}"
      with_items: '{{ site_details }}'

    - name: Wait 2 Seconds
      wait_for:
        timeout: 2

    - name: Get Site ID for The Floor
      cisco.dnac.site_info:
        <<: *dnac_conn
        name: "{{ site_name }}"
      register: site_result 

    - name: Add Devices to DNAC Inventory
      cisco.dnac.network_device:
        <<: *dnac_conn
        state: present
        cliTransport: "{{ item.cli_transport }}"
        ipAddress:
        - "{{ item.ip }}"
        userName: "{{ item.username }}"
        password: "{{ item.password }}"
        snmpRWCommunity: "{{ item.snmp_rw }}"
        snmpVersion: "{{ item.snmp_version }}"
        netconfPort: "{{ item.netconf_port }}"
      with_items: '{{ device_details }}'

    - name: Wait 2 Seconds
      wait_for:
        timeout: 2

    - name: Assign Devices to Floor
      cisco.dnac.assign_device_to_site:
        <<: *dnac_conn
        device:
        - ip: "{{ item.ip }}"
        siteId: "{{ site_result.dnac_response.response[0].id }}"
      with_items: '{{ device_details }}'  