---
# Deploy base config to core switch and use genie parser to show diffs in debug

#Specify Host Group to use
- hosts: core
  gather_facts: no
  connection: ansible.netcommon.network_cli
  roles:
    - ansible-pyats

#Specify Tasks to perform
  tasks:
    - name: Prerun Config Collection
      cisco.ios.ios_command: 
        commands: show run
      register: prior_config

    - name: Apply Initial Configuration
      cisco.ios.ios_config:
        src: "~/ansible_lab/templates/core_config.j2"
        save_when: changed

    - name: Post-Run Config Collection
      cisco.ios.ios_command: 
        commands: show run
      register: post_config
    
    - name: Show Lines Added to Config
      debug:
        msg: "{{ prior_config.stdout[0] | genie_config_diff(post_config.stdout[0], mode='add', exclude=exclude_list) }}"

  vars:
    exclude_list:
      - (^Using.*)
      - (Building.*)
      - (Current.*)
      - (crypto pki certificate chain.*)
