---
# Modify Hostname on WAN Router

- hosts: wan
  connection: ansible.netcommon.network_cli
  gather_facts: no
    
  tasks:
    - name: Modify Router Hostname
      cisco.ios.ios_hostname:
        config:
          hostname: # Enter hostname as wan-pod#
        state: replaced  
